# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.14.9

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4
    branches:
      only:
        - master
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/sliaptsou/13_docker_lading
    steps:
      - checkout
      - setup_remote_docker

      # specify any bash command here prefixed with `run: `
      - run: go get -v -t -d ./...
      - run: go test -v -cover
      - run:
          name: Build application container
          command: |
            docker build -t sliaptsou/13_docker_lading .
      - run:
          name: Login to dockerhub
          command: |
            docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASS}
      - run:
          name: Push image
          command: |
            docker push sliaptsou/13_docker_lading